export { default as goodsRoute } from './goodsRoute'
export { default as productRoute } from './productRoute'
export { default as homeRoute } from './homeRoute'
export { default as userRoute } from './userRoute'
export { default as cartRoute } from './cartRoute'
export { default as accountRoute } from './accountRoute'
export { default as bookingRoute } from './bookingRoute'
